USE `paoloweb` ;

INSERT INTO `project` (`url_image`, `title`, `description`, `github`, `link`) VALUES (NULL,'Rubik','rubik','https://github.com/pzilioti/rubik',NULL);
INSERT INTO `project` (`url_image`, `title`, `description`, `github`, `link`) VALUES ('hanafanyi.png','Hana Fanyi','hanafanyi','https://github.com/pzilioti/hanafanyi','http://www.hanafanyi.com');
INSERT INTO `project` (`url_image`, `title`, `description`, `github`, `link`) VALUES ('ziliotidev.png','zilioti.dev','ziliotidev','https://github.com/pzilioti/zilioti.dev','https://www.zilioti.dev');
INSERT INTO `project` (`url_image`, `title`, `description`, `github`, `link`) VALUES (NULL,'Homeserver','homeserver','https://github.com/pzilioti/homeserver-wol',NULL);
INSERT INTO `project` (`url_image`, `title`, `description`, `github`, `link`) VALUES ('mobile.png','Mobile Project','mobile','https://github.com/pzilioti/mobile-proj-final',NULL);
INSERT INTO `project` (`url_image`, `title`, `description`, `github`, `link`) VALUES ('endochecker.png','Endochecker','endochecker',NULL,'https://play.google.com/store/apps/details?id=app.kori.bruno_cesar_fotos');

INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('en','title','Paolo Zilioti');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('en','home','Home');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('en','projects','Projects');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('en','blog','Blog');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('en','language','Languages');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('en','self_introduction','I am a Full Stack developer with more than five years of experience in software development. I am graduated in Information Systems at University of Sao Paulo, have a certification in Java 8, and I am currently specializing in cloud computing, especially aws and kubernetes.');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('pt','self_introduction','Eu sou um desenvolvedor Full Stack com mais de 5 anos de experiência em desenvolvimento de software. Me formei em Sistemas de Informação na Universidade de São Paulo, possuo certificação em Java 8 e atualmente estou me especializando em computação na nuvem, especialmente aws e kubernetes.');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('en','latest_blog','Latest blog post:');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('en','footer','Developed by Paolo');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('en','github','Github');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('en','visit','Visit');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('pt','title','Paolo Zilioti');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('pt','home','Inicio');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('pt','projects','Projetos');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('pt','blog','Blog');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('pt','language','Idiomas');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('pt','latest_blog','Última postagem no blog:');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('pt','footer','Desenvolvido por Paolo');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('pt','github','Github');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('pt','visit','Visitar');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('en','hanafanyi','A webpage that showcase my hobby as a language learner and translator. Technology used is HTML, Javascript and CSS');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('pt','hanafanyi','Uma pagina que mostra meu hobby como estudante de idiomas e tradutor. Tecnologias usadas são HTML, Javascript e CSS');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('en','ziliotidev','This page, my virtual portfolio. Technology used is Java EE with mysql as a database');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('pt','ziliotidev','Esta pagina, meu portfolio virtual. Tecnologias usadas são Java EE com mysql no banco de dados');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('en','rubik','Rubik simulator. It can represent a cube, do any movement and currently it have a backtracking solver. Technology used is Java');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('pt','rubik','Simulador de um cubo mágico. Ele representa um cubo e realiza qualquer movimento. Atualmente possui um resolvedor que usa backtracking. Tecnologia usada é Java');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('en','welcome_project','Welcome to my projects page');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('pt','welcome_project','Bem vindo à pagina dos meus projetos');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('en','headline','Seeing the world through code.');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('pt','headline','Vendo o mundo através de código.');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('en','homeserver','A series of projects used to control the servers I run at home. Right now I have an internal endpoint to turn on the servers using wake-on-lan packages and a service that updates my ip at google domains ddns service');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('pt','homeserver','Uma série de projetos usados para controlar os servidores que uso na minha casa. No momento tenho um endpoint interno para ligar os servidores usando wake-on-lan e um serviço que atualiza meu ip no serviço de ddns do google domains');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('en','mobile','Final project for the course of Mobile Development at university. App done with react native and expo ');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('pt','mobile','Projeto final do curso de desenvolvimento mobile na universidade. App foi feito em react native com expo');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('en','endochecker','Freelance project. App used to compare pictures and display medical information of a doctor''s patients. Technology used is react native with expo');
INSERT INTO `content` (`locale`, `key`, `value`) VALUES ('pt','endochecker','Projeto freelance. Aplicativo usado para comparar fotos e exibir informações médicas de pacientes de um médico. Tecnologia usada é react native com expo');